-- Profile retention timestamps, marketing opt-in, and granular usage_events log.
-- Applied via Supabase MCP migration add_usage_tracking_and_marketing_opt_in.

alter table public.profiles
  add column if not exists first_login timestamptz,
  add column if not exists last_login timestamptz,
  add column if not exists marketing_opt_in boolean not null default false;

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in (
    'demo_site_created', 'facebook_dm_copied', 'sms_sent', 'csv_page_exported'
  )),
  lead_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_usage_events_user_created
  on public.usage_events (user_id, created_at desc);

alter table public.usage_events enable row level security;

drop policy if exists usage_events_select_own on public.usage_events;
create policy usage_events_select_own
  on public.usage_events for select
  using (auth.uid() = user_id);

-- Monthly CRM outreach limits (maps usage_events to legacy action_type labels).

create or replace function public.crm_usage_monthly_summary(p_user_id uuid)
returns table(
  action_type text,
  event_count bigint
)
language sql
stable
security definer
set search_path to 'public'
as $function$
  select
    case e.event_type
      when 'facebook_dm_copied' then 'dm'
      when 'sms_sent' then 'sms'
      when 'demo_site_created' then 'demo_click'
    end as action_type,
    count(*)::bigint as event_count
  from public.usage_events e
  where e.user_id = p_user_id
    and e.created_at >= date_trunc('month', now() at time zone 'UTC')
    and e.event_type in ('facebook_dm_copied', 'sms_sent', 'demo_site_created')
  group by 1
  order by 1;
$function$;

create or replace function public.crm_usage_monthly_total(p_user_id uuid)
returns bigint
language sql
stable
security definer
set search_path to 'public'
as $function$
  select count(*)::bigint
  from public.usage_events e
  where e.user_id = p_user_id
    and e.created_at >= date_trunc('month', now() at time zone 'UTC')
    and e.event_type in ('facebook_dm_copied', 'sms_sent', 'demo_site_created');
$function$;

-- Admin CRM usage stats (all granular event types).

create or replace function public.admin_crm_usage_stats(p_period_start timestamptz default null)
returns table(
  segment text,
  user_id uuid,
  action_type text,
  event_count bigint
)
language sql
stable
security definer
set search_path to 'public'
as $function$
  select
    case
      when p.is_pro then 'paid'
      else 'free_logged_in'
    end as segment,
    e.user_id,
    e.event_type as action_type,
    count(*)::bigint as event_count
  from public.usage_events e
  left join public.profiles p on p.id = e.user_id
  where p_period_start is null or e.created_at >= p_period_start
  group by segment, e.user_id, e.event_type
  order by segment, e.user_id, e.event_type;
$function$;

-- Per-user activity report with retention and marketing opt-in.

drop function if exists public.admin_user_activity_report(timestamptz);

create function public.admin_user_activity_report(p_period_start timestamptz default null)
returns table(
  user_id uuid,
  email text,
  is_pro boolean,
  first_login timestamptz,
  last_login timestamptz,
  marketing_opt_in boolean,
  last_sign_in_at timestamptz,
  csv_download_count bigint,
  outreach_count bigint
)
language sql
stable
security definer
set search_path to 'public'
as $function$
  select
    p.id as user_id,
    coalesce(p.email, u.email) as email,
    p.is_pro,
    p.first_login,
    p.last_login,
    p.marketing_opt_in,
    u.last_sign_in_at,
    coalesce(csv.download_count, 0)::bigint as csv_download_count,
    coalesce(outreach.event_count, 0)::bigint as outreach_count
  from public.profiles p
  inner join auth.users u on u.id = p.id
  left join (
    select
      d.user_id,
      count(*)::bigint as download_count
    from public.csv_downloads d
    where d.user_id is not null
      and (p_period_start is null or d.downloaded_at >= p_period_start)
    group by d.user_id
  ) csv on csv.user_id = p.id
  left join (
    select
      e.user_id,
      count(*)::bigint as event_count
    from public.usage_events e
    where e.event_type in ('facebook_dm_copied', 'sms_sent', 'demo_site_created')
      and (p_period_start is null or e.created_at >= p_period_start)
    group by e.user_id
  ) outreach on outreach.user_id = p.id
  order by p.last_login desc nulls last, u.last_sign_in_at desc nulls last, p.email;
$function$;
