-- Conversion tracking: when a no-website lead acquires a real website on re-scrape.

alter table public.businesses_nowebsite
  add column if not exists first_seen_without_website date,
  add column if not exists website_acquired_date date,
  add column if not exists converted boolean not null default false,
  add column if not exists last_checked timestamptz;

comment on column public.businesses_nowebsite.first_seen_without_website is
  'Calendar date we first recorded this listing without a real website.';
comment on column public.businesses_nowebsite.website_acquired_date is
  'Calendar date a re-scrape first detected their own website.';
comment on column public.businesses_nowebsite.converted is
  'True after website_acquired_date is set (one-way).';
comment on column public.businesses_nowebsite.last_checked is
  'Last time any scrape pass touched this row.';

update public.businesses_nowebsite
set first_seen_without_website = scraped_at::date
where has_website = false
  and first_seen_without_website is null
  and scraped_at is not null;

create table if not exists public.conversion_stats (
  id bigint generated by default as identity primary key,
  place_id text not null,
  category text,
  website_found_on date not null,
  first_seen_without_website date,
  days_to_convert integer,
  name text,
  address text,
  city text,
  state text,
  country text,
  postal_code text,
  latitude double precision,
  longitude double precision,
  main_category text,
  business_type text,
  rating double precision,
  reviews integer,
  phone text,
  google_maps_link text,
  listing_website text not null,
  recorded_at timestamptz not null default now()
);

comment on table public.conversion_stats is
  'Append-only log when a previously no-website GBP listing gains a real website on refresh.';

create index if not exists idx_conversion_stats_website_found_on
  on public.conversion_stats (website_found_on desc);

create index if not exists idx_conversion_stats_place_id
  on public.conversion_stats (place_id);

create index if not exists idx_conversion_stats_category
  on public.conversion_stats (category);

create index if not exists idx_businesses_nowebsite_converted
  on public.businesses_nowebsite (converted)
  where converted = true;
