-- Country batch orchestration for local Python scrape runs.

create table if not exists public.scrape_batches (
  id bigint generated by default as identity primary key,
  business_type text not null,
  country text not null default 'US',
  strategy text not null default 'per_state',
  state_filter text,
  max_results_per_location int not null default 25,
  dry_run boolean not null default false,
  status text not null default 'pending',
  total_locations int not null default 0,
  completed_locations int not null default 0,
  failed_locations int not null default 0,
  skipped_locations int not null default 0,
  rows_scraped int not null default 0,
  rows_emitted int not null default 0,
  error_message text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_scrape_batches_status_created
  on public.scrape_batches (status, created_at desc);

create table if not exists public.scrape_batch_locations (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.scrape_batches (id) on delete cascade,
  location_hint text not null,
  state text,
  status text not null default 'pending',
  rows_scraped int not null default 0,
  rows_emitted int not null default 0,
  sweet_spot_fail int not null default 0,
  skipped_no_place_id int not null default 0,
  skipped_min_recent_reviews int not null default 0,
  has_website int not null default 0,
  error_message text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (batch_id, location_hint)
);

create index if not exists idx_scrape_batch_locations_batch_status
  on public.scrape_batch_locations (batch_id, status);

create index if not exists idx_scrape_batch_locations_business_location
  on public.scrape_batch_locations (location_hint, finished_at desc);

create or replace function public.set_scrape_batches_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_scrape_batches_updated_at on public.scrape_batches;
create trigger trg_scrape_batches_updated_at
before update on public.scrape_batches
for each row execute function public.set_scrape_batches_updated_at();

create or replace function public.set_scrape_batch_locations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_scrape_batch_locations_updated_at on public.scrape_batch_locations;
create trigger trg_scrape_batch_locations_updated_at
before update on public.scrape_batch_locations
for each row execute function public.set_scrape_batch_locations_updated_at();
