-- Separate job queue table for nowebsite scraping pipeline.
-- Keeps status tracking isolated from legacy/sweatydata jobs.

create table if not exists public.scrape_jobs_nowebsite (
  id bigint generated by default as identity primary key,
  task_id bigint not null unique,
  business_type text not null,
  zip_code text,
  status text not null default 'pending',
  loaded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_scrape_jobs_nowebsite_status_loaded
  on public.scrape_jobs_nowebsite (status, loaded_at);

create or replace function public.set_scrape_jobs_nowebsite_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_scrape_jobs_nowebsite_updated_at on public.scrape_jobs_nowebsite;
create trigger trg_scrape_jobs_nowebsite_updated_at
before update on public.scrape_jobs_nowebsite
for each row execute function public.set_scrape_jobs_nowebsite_updated_at();
