-- Create a dedicated table for demo-ready no-website businesses.
-- Replay-safe: run in Supabase SQL editor.

create table if not exists public.businesses_nowebsite (
  id bigint generated by default as identity primary key,
  place_id text not null,

  name text,
  address text,
  city text,
  state text,
  country text not null default 'US',
  postal_code text,
  latitude double precision,
  longitude double precision,

  main_category text,
  business_type text,
  rating double precision,
  reviews integer,
  is_spending_on_ads boolean,
  has_website boolean not null default false,

  phone text,
  google_maps_link text,
  facebook_url text,
  listing_website text,
  crm_contact_surface text generated always as (
    case
      when nullif(trim(coalesce(facebook_url, '')), '') is not null then 'facebook'
      when listing_website is not null
        and nullif(trim(listing_website), '') is not null
        and listing_website ~* 'wa\.me|whatsapp\.com' then 'whatsapp'
      when listing_website is not null
        and nullif(trim(listing_website), '') is not null
        and listing_website ~* 'facebook\.com|fb\.com|fb\.me' then 'facebook'
      else 'none'
    end
  ) stored,
  contact_count integer not null default 0,

  competitive_weakness text,
  contact_enrichment jsonb,
  enriched_at timestamptz,

  -- Demo SEO enrichment fields
  review_highlights jsonb,
  services_offered text[],
  hours jsonb,
  open_now boolean,
  review_highlights_updated_at timestamptz,

  -- Pipeline/job bookkeeping
  scraped_at timestamptz not null default now(),
  source_snapshot_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint businesses_nowebsite_country_check check (country in ('US', 'GB')),
  constraint businesses_nowebsite_place_id_key unique (place_id),
  constraint businesses_nowebsite_contact_count_check
    check (contact_count >= 0 and contact_count <= 50)
);

-- Helpful indexes for CRM/demo query patterns
create index if not exists idx_businesses_nowebsite_place_id
  on public.businesses_nowebsite (place_id);

create index if not exists idx_businesses_nowebsite_crm_leads
  on public.businesses_nowebsite (reviews desc, rating desc)
  where has_website = false;

create index if not exists idx_businesses_nowebsite_open_now
  on public.businesses_nowebsite (open_now)
  where has_website = false;

create index if not exists idx_businesses_nowebsite_state_type
  on public.businesses_nowebsite (state, business_type);

create index if not exists idx_businesses_nowebsite_crm_contact_surface
  on public.businesses_nowebsite (crm_contact_surface)
  where has_website = false;

-- Keep updated_at fresh if you use normal UPDATE statements.
create or replace function public.set_businesses_nowebsite_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_businesses_nowebsite_updated_at on public.businesses_nowebsite;
create trigger trg_businesses_nowebsite_updated_at
before update on public.businesses_nowebsite
for each row execute function public.set_businesses_nowebsite_updated_at();

-- Optional one-time bootstrap from current table:
-- insert into public.businesses_nowebsite (
--   place_id, name, address, city, state, postal_code, latitude, longitude,
--   main_category, business_type, rating, reviews, is_spending_on_ads, has_website,
--   phone, google_maps_link, facebook_url, contact_count, competitive_weakness,
--   contact_enrichment, enriched_at, review_highlights, services_offered, hours,
--   open_now, review_highlights_updated_at, scraped_at, source_snapshot_at
-- )
-- select
--   place_id, name, address, city, state, postal_code, latitude, longitude,
--   main_category, business_type, rating, reviews, is_spending_on_ads, has_website,
--   phone, google_maps_link, facebook_url, coalesce(contact_count, 0), competitive_weakness,
--   contact_enrichment, enriched_at, review_highlights, services_offered, hours,
--   open_now, review_highlights_updated_at, coalesce(scraped_at, now()), now()
-- from public.businesses
-- where has_website = false
-- on conflict (place_id) do update
-- set
--   name = excluded.name,
--   address = excluded.address,
--   city = excluded.city,
--   state = excluded.state,
--   postal_code = excluded.postal_code,
--   latitude = excluded.latitude,
--   longitude = excluded.longitude,
--   main_category = excluded.main_category,
--   business_type = excluded.business_type,
--   rating = excluded.rating,
--   reviews = excluded.reviews,
--   is_spending_on_ads = excluded.is_spending_on_ads,
--   has_website = excluded.has_website,
--   phone = excluded.phone,
--   google_maps_link = excluded.google_maps_link,
--   facebook_url = excluded.facebook_url,
--   contact_count = excluded.contact_count,
--   competitive_weakness = excluded.competitive_weakness,
--   contact_enrichment = excluded.contact_enrichment,
--   enriched_at = excluded.enriched_at,
--   review_highlights = excluded.review_highlights,
--   services_offered = excluded.services_offered,
--   hours = excluded.hours,
--   open_now = excluded.open_now,
--   review_highlights_updated_at = excluded.review_highlights_updated_at,
--   scraped_at = excluded.scraped_at,
--   source_snapshot_at = excluded.source_snapshot_at;
