-- Monthly outreach usage tracking for free CRM tier (DM, SMS, demo clicks).
-- Applied via Supabase MCP migration create_crm_usage_events.

create table if not exists public.crm_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action_type text not null check (action_type in ('dm', 'sms', 'demo_click')),
  place_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_crm_usage_events_user_created
  on public.crm_usage_events (user_id, created_at desc);

alter table public.crm_usage_events enable row level security;

drop policy if exists crm_usage_events_select_own on public.crm_usage_events;
create policy crm_usage_events_select_own
  on public.crm_usage_events for select
  using (auth.uid() = user_id);
