-- Lead capture for directory CSV exports.

create table if not exists public.csv_downloads (
  id bigint generated by default as identity primary key,
  email text not null,
  page_url text not null,
  downloaded_at timestamptz not null default now()
);

create index if not exists idx_csv_downloads_downloaded_at
  on public.csv_downloads (downloaded_at desc);

create index if not exists idx_csv_downloads_email
  on public.csv_downloads (email);
