-- Run history for scrape/extract-local-extractor-cache.mjs (Task Scheduler, etc.).
-- Apply in Supabase SQL editor. Service role inserts from Node; app reads via service on server.

create table if not exists public.extract_local_cache_runs (
  id bigint generated by default as identity primary key,
  run_at timestamptz not null default now(),
  duration_ms integer not null default 0,
  exit_code smallint not null default 0,
  extractor_root text,
  business_type text,
  dry_run boolean not null default false,
  businesses_target_table text,
  cache_files_scanned integer not null default 0,
  lines_read integer not null default 0,
  skipped_no_place_id integer not null default 0,
  skipped_duplicate_place integer not null default 0,
  skipped_has_website integer not null default 0,
  skipped_sweet_spot integer not null default 0,
  matched_leads integer not null default 0,
  businesses_upserted integer not null default 0,
  upsert_batch_errors integer not null default 0,
  json_parse_errors integer not null default 0,
  files_deleted integer not null default 0,
  files_delete_failed integer not null default 0,
  pending_cache_deletes integer not null default 0,
  error_message text,
  filter_snapshot jsonb
);

create index if not exists idx_extract_local_cache_runs_run_at
  on public.extract_local_cache_runs (run_at desc);

comment on table public.extract_local_cache_runs is
  'Append-only log for local Google Maps extractor cache → Supabase pipeline (extract-local-extractor-cache.mjs).';
